config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.

  get "up" => "rails/health#show", as: :rails_health_check

  root to: "pages#home"

  devise_for :users

  resources :consultations, only: :index

  resources :favourites, only: [:index, :destroy]

  resources :properties do
    resources :consultations, only: [:new, :create]
    resources :favourites, only: :create
  end

  get "/user_properties", to: 'properties#user_properties', as: 'user_properties'

  get "/faqs", to: 'pages#faqs', as: 'faqs'

  get "/services", to: 'pages#services', as: 'services'

  get "/subscribe", to: 'subscribers#create', as: 'subscribe'

  delete "properties/:id", to: "properties#destroy", as: 'delete_user_property'

  get "/user_properties/edit", to: "properties#edit"

  patch "/user_properties", to: "properties#update"

  post '/favourites/:property_id', to: "favourites#create"
  delete '/favourites/:id', to: "favourites#destroy"
end

# HUGH'S CUSTOM ROUTES THAT I AM UNSURE WHETHER WE WILL KEEP
# get '/user_bookings', to: 'bookings#user_bookings', as: 'user_bookings'
# get "search_result", to: 'properties#search_result', as: 'search_result'
#get '/user_properties/property_bookings', to: 'bookings#property_bookings', as: 'property_bookings'

app/models/favourite.rb
class Favourite < ApplicationRecord
  belongs_to :user
  belongs_to :property
end

app/controllers/favourites_controller.rb
class FavouritesController < ApplicationController
  def index
    @favourites = Favourite.where(user: current_user)

    fav_properties = Property.includes(:favourites).where(favourites: { user: current_user })

    @markers = fav_properties.geocoded.map do |property|
      {
        lat: property.latitude,
        lng: property.longitude,
        info_window_html: render_to_string(partial: "properties/info_window", locals: {property: property}),
        marker_html: render_to_string(partial: "properties/marker", locals: {property: property})
      }
    end
  end

  def create
    favourite = Favourite.new
    property = Property.find(params[:property_id])
    favourite.property = property
    favourite.user = current_user
    if favourite.save
      redirect_to properties_path
    else
      @properties = Property.all
      p favourite.errors.messages
      render 'pages/home'
    end
  end

  def destroy
    favourite = Property.find(params[:id]).favourited_by(current_user)
    favourite.destroy
    # redirect_to request.referer
    redirect_to properties_path
  end

end

app/views/favourites/_actions.html.erb
<% if user_signed_in? %>
  <% unless property.user == current_user %>
    <% favourite = property.favourited_by(current_user) %>
    <div data-controller="favourite" data-favourite-property-id-value="<%= property.id %>">
      <% unless favourite %>
        <%= link_to property_favourites_path(property), data: { action: 'click->favourite#send', favourite_target: 'link' }, class: "pin" do %>
          <i class="fa-regular fa-heart" data-favourite-target="icon"></i>
        <% end %>
      <% else %>
        <%= link_to favourite_path(favourite), data: { action: 'click->favourite#send', favourite_target: 'link' }, class: "pin" do %>
          <i class="fa-solid fa-heart" data-favourite-target="icon"></i>
        <% end %>
      <% end %>
    </div>
  <% end %>
<% else %>
  <%= link_to  new_user_session_path, class: "pin" do %>
    <i class="fa-regular fa-heart"></i>
  <% end %>
<% end %>

app/views/favourites/index.html.erb
<h1 class="text-center">Favourite Properties</h1>
<br>
<div class="row">
  <div class="col-7">
    <div class="property-grid">
      <% @favourites.each do |favourite| %>
        <%= render "properties/property", property: favourite.property %>
      <% end %>
    </div>
  </div>
  <div class="col-5">
    <div id="map"
      data-controller="map"
      data-map-markers-value="<%= @markers.to_json %>"
      data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
  </div> <!-- Close Right Column -->
</div> <!-- Close Row -->