config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.

  get "up" => "rails/health#show", as: :rails_health_check

  root to: "pages#home"

  devise_for :users

  resources :consultations, only: :index

  resources :favourites, only: [:index, :destroy]

  resources :properties do
    resources :consultations, only: [:new, :create]
    resources :favourites, only: :create
  end

  get "/user_properties", to: 'properties#user_properties', as: 'user_properties'

  get "/faqs", to: 'pages#faqs', as: 'faqs'

  get "/services", to: 'pages#services', as: 'services'

  get "/subscribe", to: 'subscribers#create', as: 'subscribe'

  delete "properties/:id", to: "properties#destroy", as: 'delete_user_property'

  get "/user_properties/edit", to: "properties#edit"

  patch "/user_properties", to: "properties#update"

  post '/favourites/:property_id', to: "favourites#create"
  delete '/favourites/:id', to: "favourites#destroy"
end

# HUGH'S CUSTOM ROUTES THAT I AM UNSURE WHETHER WE WILL KEEP
# get '/user_bookings', to: 'bookings#user_bookings', as: 'user_bookings'
# get "search_result", to: 'properties#search_result', as: 'search_result'
#get '/user_properties/property_bookings', to: 'bookings#property_bookings', as: 'property_bookings'

app/models/property.rb
class Property < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many_attached :photos


  has_many :images, dependent: :destroy

  def image_urls
    urls = images.map { |img| img.url }
    photos.each do |photo|
      urls << "https://res.cloudinary.com/dna9z7j4z/image/upload/v1/#{ENV["RAILS_ENV"]}/#{photo.key}"
    end
    urls
  end

  has_many :favourites, dependent: :destroy

  geocoded_by :address

  validates :prefecture, inclusion: { in: ["Aichi", "Akita", "Aomori", "Chiba", "Ehime", "Fukui", "Fukuoka", "Fukushima", "Gifu", "Gunma", "Hiroshima", "Hokkaido", "Hyogo", "Ibaraki", "Ishikawa", "Iwate", "Kagawa", "Kagoshima", "Kanagawa", "Kochi", "Kumamoto", "Kyoto", "Mie", "Miyagi", "Miyazaki", "Nagano", "Nagasaki", "Nara", "Niigata", "Oita", "Okayama", "Okinawa", "Osaka", "Saga", "Saitama", "Shiga", "Shimane", "Shizuoka", "Tochigi", "Tokushima", "Tokyo", "Tottori", "Toyama", "Wakayama", "Yamagata", "Yamaguchi", "Yamanashi"] }
  after_validation :geocode_if_needed

  def geocode_if_needed
      if will_save_change_to_address? && latitude.nil?
          geocode
      end
  end

  # def geocode_property
  #   if latitude.nil? || longitude.nil?
  #     lat_long = geocode
  #     latitude = lat_long.first
  #     longitude = lat_long.last
  #   end
  # end
  #


  def favourited_by(user)
    Favourite.find_by(user: user, property: self)
  end

  def favorite_count
    Favourite.where(property_id: self.id).count
  end

  def view_count
    self.views
  end
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    # @properties = Property.geocoded.map
    @properties = Property.all
    if params[:query].present?
      sql_subquery = "city ILIKE :query OR prefecture ILIKE :query"
      @properties = @properties.where(sql_subquery, query: "%#{params[:query]}%")
    end
    if params[:min_price].present?
      @properties = @properties.where("price >= ?", params[:min_price].to_f)
    end
    if params[:max_price].present?
      @properties = @properties.where("price <= ?", params[:max_price].to_f)
    end
    if params[:bedrooms].present?
      @properties = @properties.where("bedrooms >= ?", params[:bedrooms].to_i)
    end
    if params[:bathrooms].present?
      @properties = @properties.where("bathrooms >= ?", params[:bathrooms].to_i)
    end
    if params[:property_type_akiya].present?
      @properties = @properties.where(property_type: "Akiya")
    end
    if params[:property_type_machiya].present?
      @properties = @properties.where(property_type: "Machiya")
    end
    if params[:property_type_kominka].present?
      @properties = @properties.where(property_type: "Kominka")
    end

    @markers = @properties.geocoded.map do |property|
      {
        lat: property.latitude,
        lng: property.longitude,
        info_window_html: render_to_string(partial: "info_window", locals: {property: property}),
        marker_html: render_to_string(partial: "marker", locals: {property: property})
      }
    end
  end

  def new
    @property = Property.new
  end

  def create
    @property = Property.new(property_params)
    @property.user = current_user
    if @property.save
      redirect_to user_properties_path, notice: 'Property was successfully created.'
    else
      render :new
    end
  end

  def destroy
    property = Property.find(params[:id])
    property.destroy
    redirect_to user_properties_path, status: :see_other
  end

  def user_properties
    @properties = Property.where(user: current_user)
  end

  def show
    @property = Property.find(params[:id])
    current_view_count = @property.views.nil? ? 0 : @property.views
    @property.update(views: current_view_count + 1)
  end

  def edit
    @property = Property.find(params[:id])
  end

  def update
    @property = Property.find(params[:id])
    @property.update(property_params) # Will raise ActiveModel::ForbiddenAttributesError
    redirect_to user_properties_path(@property)
  end



  private

  def property_params
    params.require(:property).permit(
    :price,
    :age,
    :city,
    :prefecture,
    :address,
    :bedrooms,
    :size_building,
    :size_land,
    :bathrooms,
    :description,
    :property_type,
    photos: [])
  end
end

app/views/properties/_edit.html.erb
<h5 class="text-center">You can modify the details of your property</h5>
  <div class="content container d-flex justify-content-center">
    <%= simple_form_for [@property] do |f| %>
      <div class="form-inputs">
        <%= f.input :price,
                    required: true,
                    autofocus: true,
                    input_html: { autocomplete: "price" }%>
        <%= f.input :property_type,
                    collection: ['Akiya', 'Machiya', 'Kominka'],
                    required: true,
                    autofocus: true %>
        <%= f.input :age,
                    required: true,
                    input_html: { autocomplete: "age"}%>
        <%= f.input :city,
                    required: true,
                    input_html: { autocomplete: "city"}%>
        <%= f.input :prefecture,
                    required: true,
                    collection: ["Hokkaido", "Aomori", "Iwate", "Miyagi", "Akita", "Yamagata", "Fukushima", "Ibaraki", "Tochigi", "Gunma", "Saitama", "Chiba", "Tokyo", "Kanagawa", "Niigata", "Toyama", "Ishikawa", "Fukui", "Yamanashi", "Nagano", "Gifu", "Shizuoka", "Aichi", "Mie", "Shiga", "Kyoto", "Osaka", "Hyogo", "Nara", "Wakayama", "Tottori", "Shimane", "Okayama", "Hiroshima", "Yamaguchi", "Tokushima", "Kagawa", "Ehime", "Kochi", "Fukuoka", "Saga", "Nagasaki", "Kumamoto", "Oita", "Miyazaki", "Kagoshima", "Okinawa"],
                    input_html: { autocomplete: "prefecture"} %>
        <%= f.input :address,
                    required: true,
                    input_html: { autocomplete: "address"}%>
        <%= f.input :bedrooms,
                    required: true,
                    input_html: { autocomplete: "bedrooms"}%>
        <%= f.input :bathrooms,
                    required: true,
                    input_html: { autocomplete: "bathrooms"}%>
        <%= f.input :size_building,
                    label: 'Size of Building',
                    placeholder: 'sq m',
                    required: true %>
        <%= f.input :size_land,
                    label: 'Size of Land',
                    placeholder: 'sq m',
                    required: true %>

        <%= f.input :description,
                    label: 'Description',
                    size: '70x5',
                    required: true,
                    input_html: { autocomplete: "description"}%>
        <%= f.input :photos, as: :file, input_html: { multiple: true } %>
      </div>

app/views/properties/_form.html.erb
<%= f.input :address,
  input_html: {data: {address_autocomplete_target: "address"}},
  wrapper_html: {data: {controller: "address-autocomplete", address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}}
%>

app/views/properties/_info_window.html.erb
 <%= render "properties/property", property: property %>

app/views/properties/_list.html.erb
  <div class="property-grid">
    <% if properties.any? %>
      <% properties.each do |property| %>
        <%= render "property", property: property %>
      <% end %>
    <% else %>
      <p>Please try to search again.</p>
    <% end %>
  </div>

app/views/properties/_marker.html.erb
<%= image_tag "logo.png", height: 30, width: 30, alt: "Logo" %>
<div class="badge rounded-pill bg-primary fs-6">
  <%= property.address %>
</div>

app/views/properties/_property.html.erb
<div class="card-search-result">
  <%= render "favourites/actions", property: property %>
  <a href="<%= property_path(property)%>" class="card-link">
    <img src="<%= property.image_urls.second %>" alt="" class="d-block" width="238" height="240">
    <br>
    <span class="prefecture">
      <p class="text-center"><%= property.city %>,
      <%= property.prefecture %></span></p>
    <p class="property-info text-center">
      <%= "#{property.bedrooms} bedrooms | #{number_to_currency(property.price)}" %></p>
  </a>
</div>

app/views/properties/edit.html.erb
<h5 class="text-center">You can modify the details of your property</h5>
  <div class="content container d-flex justify-content-center">
    <%= simple_form_for [@property] do |f| %>
      <div class="form-inputs">
        <%= f.input :price,
                    required: true,
                    autofocus: true,
                    input_html: { autocomplete: "price" }%>
        <%= f.input :property_type,
                    collection: ['Akiya', 'Machiya', 'Kominka'],
                    required: true,
                    autofocus: true %>
        <%= f.input :age,
                    required: true,
                    input_html: { autocomplete: "age"}%>
        <%= f.input :city,
                    required: true,
                    input_html: { autocomplete: "city"}%>
        <%= f.input :prefecture,
                    required: true,
                    collection: ["Hokkaido", "Aomori", "Iwate", "Miyagi", "Akita", "Yamagata", "Fukushima", "Ibaraki", "Tochigi", "Gunma", "Saitama", "Chiba", "Tokyo", "Kanagawa", "Niigata", "Toyama", "Ishikawa", "Fukui", "Yamanashi", "Nagano", "Gifu", "Shizuoka", "Aichi", "Mie", "Shiga", "Kyoto", "Osaka", "Hyogo", "Nara", "Wakayama", "Tottori", "Shimane", "Okayama", "Hiroshima", "Yamaguchi", "Tokushima", "Kagawa", "Ehime", "Kochi", "Fukuoka", "Saga", "Nagasaki", "Kumamoto", "Oita", "Miyazaki", "Kagoshima", "Okinawa"],
                    input_html: { autocomplete: "prefecture"} %>
        <%= f.input :address,
                    required: true,
                    input_html: { autocomplete: "address"}%>
        <%= f.input :bedrooms,
                    required: true,
                    input_html: { autocomplete: "bedrooms"}%>
        <%= f.input :bathrooms,
                    required: true,
                    input_html: { autocomplete: "bathrooms"}%>
        <%= f.input :size_building,
                    label: 'Size of Building',
                    placeholder: 'sq m',
                    required: true %>
        <%= f.input :size_land,
                    label: 'Size of Land',
                    placeholder: 'sq m',
                    required: true %>

        <%= f.input :description,
                    label: 'Description',
                    size: '70x5',
                    required: true,
                    input_html: { autocomplete: "description"}%>
        <%= f.input :photos, as: :file, input_html: { multiple: true } %>
        <button class="mt-3">Submit</button>
      </div>
      <% end %>

app/views/properties/index.html.erb
<h1>Search Result</h1>
<br>
<div class="row">
  <!-- Left Column with Search Bar and Property Cards -->
  <div class="col-7">
    <!-- Search Bar -->
    <%= form_with url: properties_path, method: :get, class: "d-flex mb-3", id: "search-form" do %>
      <div class="col-md-6">
        <%= text_field_tag :query, params[:query], class: "form-control rounded-pill", placeholder: "Search by Prefecture", id: "prefecture-search" %>
      </div>
      <div class="col-md-3">
        <%= submit_tag "Search", name: "", class: "btn btn-primary" %>
        <!-- Button trigger modal -->
        <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#filterModal">
          Filter
        </button>
      </div>

      <!-- Modal -->
      <div class="modal fade" id="filterModal" tabindex="-1" aria-labelledby="filterModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h1 class="modal-title fs-5" id="filterModalLabel">Filters</h1>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
              <div class="property-type my-3">
                <label>Property type</label>
                <div class="btn-group btn-group-toggle d-flex" data-toggle="buttons">
                  <label class="btn btn-outline-dark flex-fill text-dark">
                    <input type="checkbox" name="property_type" id="any"> Any
                  </label>
                  <label class="btn btn-outline-dark flex-fill text-dark">
                    <input type="checkbox" name="property_type_akiya" id="akiya"> Akiya
                  </label>
                  <label class="btn btn-outline-dark flex-fill text-dark">
                    <input type="checkbox" name="property_type_machiya" id="machiya"> Machiya
                  </label>
                  <label class="btn btn-outline-dark flex-fill text-dark">
                    <input type="checkbox" name="property_type_kominka" id="kominka"> Kominka
                  </label>
                </div>
              </div>

              <div class="price-range">
                <label>Price range</label>
                <div class="price-inputs">
                  <input type="text" class="form-control" id="min_price" name="min_price" placeholder="Min" oninput="syncRangeMin()">
                  <input type="text" class="form-control" id="max_price" name="max_price" placeholder="Max" oninput="syncRangeMax()">
                </div>
              </div>

              <div class="rooms-container">
                <div>
                  <label>Bedrooms</label>
                  <select class="form-control" id="modal-bedrooms" name="bedrooms">
                    <option>Any</option>
                    <option>1</option>
                    <option>2</option>
                    <option>3</option>
                    <option>4+</option>
                  </select>
                </div>
                <div>
                  <label>Bathrooms</label>
                  <select class="form-control" id="modal-bathrooms" name="bathrooms">
                    <option>Any</option>
                    <option>1</option>
                    <option>2</option>
                    <option>3</option>
                    <option>4+</option>
                  </select>
                </div>
              </div>

              <div class="footer-buttons">
                <button type="button" class="btn btn-secondary" id="clear-filters">Clear all filters</button>
                  <%= submit_tag "Search", name: "", class: "btn btn-primary" %>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>

    <!-- Property Counter -->
    <div class="property-counter">
      <% if @properties.present? %>
        <p><%= @properties.size %> properties found</p>
      <% else %>
        <p>No properties found</p>
      <% end %>
    </div>

    <!-- Render Property List -->
    <%= render "list", properties: @properties %>
  </div> <!-- Close Left Column -->

  <!-- Right Column with Map -->
  <div class="col-5">
    <div id="map"
      data-controller="map"
      data-map-markers-value="<%= @markers.to_json %>"
      data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
  </div> <!-- Close Right Column -->
</div> <!-- Close Row -->

<!-- JavaScript to link the "Show" button with the "Search" button -->
<script>
  document.getElementById('clear-filters').addEventListener('click', function() {
    document.getElementById('modal-bedrooms').value = 'Any';
    document.getElementById('modal-bathrooms').value = 'Any';
    document.getElementById('min_price').value = '';
    document.getElementById('max_price').value = '';
  });
</script>

app/views/properties/new.html.erb
<div class='new-property'>
  <h1>List Your Property</h1>
  <h5 class="text-center">Please enter the details of your property</h5>
  <div class="content container d-flex justify-content-center">
    <%= simple_form_for [@property] do |f| %>
      <div class="form-inputs">
        <%= f.input :price,
                    required: true,
                    autofocus: true,
                    input_html: { autocomplete: "price" }%>
        <%= f.input :property_type,
                    collection: ['Akiya', 'Machiya', 'Kominka'],
                    required: true,
                    autofocus: true %>
        <%= f.input :age,
                    required: true,
                    input_html: { autocomplete: "age"}%>
        <%= f.input :city,
                    required: true,
                    input_html: { autocomplete: "city"}%>
        <%= f.input :prefecture,
                    required: true,
                    collection: ["Aichi", "Akita", "Aomori", "Chiba", "Ehime", "Fukui", "Fukuoka", "Fukushima", "Gifu", "Gunma", "Hiroshima", "Hokkaido", "Hyogo", "Ibaraki", "Ishikawa", "Iwate", "Kagawa", "Kagoshima", "Kanagawa", "Kochi", "Kumamoto", "Kyoto", "Mie", "Miyagi", "Miyazaki", "Nagano", "Nagasaki", "Nara", "Niigata", "Oita", "Okayama", "Okinawa", "Osaka", "Saga", "Saitama", "Shiga", "Shimane", "Shizuoka", "Tochigi", "Tokushima", "Tokyo", "Tottori", "Toyama", "Wakayama", "Yamagata", "Yamaguchi", "Yamanashi"],
                    input_html: { autocomplete: "prefecture"} %>
        <%= f.input :address,
                    required: true,
                    input_html: { autocomplete: "address"}%>
        <%= f.input :bedrooms,
                    required: true,
                    input_html: { autocomplete: "bedrooms"}%>
        <%= f.input :bathrooms,
                    required: true,
                    input_html: { autocomplete: "bathrooms"}%>
        <%= f.input :size_building,
                    label: 'Size of Building',
                    placeholder: 'sq m',
                    required: true %>
        <%= f.input :size_land,
                    label: 'Size of Land',
                    placeholder: 'sq m',
                    required: true %>

        <%= f.input :description,
                    label: 'Description',
                    size: '70x5',
                    required: true,
                    input_html: { autocomplete: "description"}%>
        <%= f.input :photos, as: :file, input_html: { multiple: true } %>
      </div>

      <div class="form-actions text-center">
          <%= f.button :submit, "Add property", class: 'button' %>
      </div>
    <% end %>
  </div>
</div>

app/views/properties/show.html.erb
<h1 class="m-5 text-center">Property No. <%= @property.id %></h1>
<div class="row">
  <div class="col-md-6">
    <div class="mb-2">
        <img src="<%= @property.image_urls.second %>" alt="" class="d-block w-100">
    </div>

    <div class="bg-white p-3 mb-3 rounded-4 bg-secondary-subtle text-secondary-emphasis">
      <% if @property.present? %>
        <div class="caption-box">
          <h4 class="text-start mb-2">Information</h4>
          <div>
            <i class="fa-solid fa-house me-3 float-start"></i>
            <p class="text-start"><%= @property.property_type %></p>
            <i class="fa-solid fa-bed me-3 float-start"></i>
            <p class="text-start"><%= "#{@property.bedrooms} #{@property.bedrooms > 1 ? 'Bedrooms' : 'Bedroom'}" %></p>
            <i class="fa-solid fa-shower me-3 float-start"></i>
            <p class="text-start"><%= "#{@property.bathrooms} #{@property.bathrooms > 1 ? 'Bathrooms' : 'Bathroom'}" %></p>
            <% if @property.size_building > 0 %>
            <i class="fa-solid fa-square me-3 float-start"></i>
            <p class="text-start"><%= "Building size: #{@property.size_building} sq m" %></p>
            <% end %>
            <% if @property.size_land > 0 %>
            <i class="fa-regular fa-square me-3 float-start"></i>
            <p class="text-start mb-2"><%= "Land size: #{@property.size_land} sq m" %></p>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>

    <div class="bg-white p-3 rounded-4 bg-secondary-subtle text-secondary-emphasis">
      <% if @property.present? %>
        <div>
          <h4 mb-2>Description</h4>
          <p><%= @property.description %></p>
        </div>
      <% end %>
    </div>
  </div>

  <div class="col-md-6">
    <div class="row row-cols-2">
        <div class="col mb-2">
            <img src="<%= @property.image_urls.first %>" alt="" class="d-block w-100">
        </div>
        <div class="col mb-2">
            <img src="<%= @property.image_urls.third %>" alt="" class="d-block w-100">
        </div>
        <div class="col mb-2">
           <img src="<%= @property.image_urls.fourth %>" alt="" class="d-block w-100">
        </div>
        <div class="col mb-2">
            <img src="<%= @property.image_urls.fifth %>" alt="" class="d-block w-100">
        </div>
      </div>
      <div class="bg-white p-3 mb-2 rounded-4 bg-secondary-subtle text-secondary-emphasis">
        <div class="details d-flex justify-content-between align-items-end mb-2">
          <%= render "favourites/actions", property: @property, user: current_user %>
            <h3 style="text-start"><%= number_to_currency(@property.price) %></h3>
          <button type="button" class="bg-secondary-subtle border-0 ms-2" data-bs-toggle="modal" data-bs-target="#exampleModal">
            <i class="bi bi-share text-black mb-2"></i>
          </button>
        </div>

      <% if @property.present? %>
        <div class="caption-box">
          <div class="mt-3 mb-3">
            <h5 class="text-start">Year built: <%= @property.age %></h5>
            <br>
            <h5 class="text-start">Address: <%= @property.address %></h5>
          </div>
        </div>
      <% end %>

      <div class="text-start">
        <%= "#{@property.favorite_count} likes, #{@property.view_count} views" %>
      </div>

      <div class="consultation-button-container d-flex justify-content-left mt-3">
        <%= link_to 'Book a Consultation', new_property_consultation_path(@property), class: "btn consultation" %>
      </div>
    </div>
  </div>
</div>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">Share</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <p>Share your property via social media:</p>
        <div class="share-buttons">
          <a href="https://facebook.com" target="_blank" data-controller="clipboard" data-action="clipboard#copy">
            <button class="share-button facebook">
              <i class="fab fa-facebook-f"></i>
            </button>
          </a>
          <a href="https://twitter.com" target="_blank" data-controller="clipboard" data-action="clipboard#copy">
            <button class="share-button twitter">
              <i class="fab fa-twitter"></i>
            </button>
          </a>
          <a href="https://instagram.com" target="_blank" data-controller="clipboard" data-action="clipboard#copy">
            <button class="share-button instagram">
              <i class="fab fa-instagram"></i>
            </button>
          </a>
          <a href="https://whatsapp.com" target="_blank" data-controller="clipboard" data-action="clipboard#copy">
            <button class="share-button whatsapp">
              <i class="fab fa-whatsapp"></i>
            </button>
          </a>
          <a href="https://messenger.com" target="_blank" data-controller="clipboard" data-action="clipboard#copy">
            <button class="share-button messenger">
              <i class="fa-brands fa-facebook-messenger"></i>
            </button>
          </a>
          <a href="https://gmail.com" target="_blank" data-controller="clipboard" data-action="clipboard#copy">
            <button class="share-button gmail">
              <i class="fa-solid fa-envelope"></i>
            </button>
          </a>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/properties/user_properties.html.erb
<h1>Your Properties</h1>

 <div class="property-grid">
    <% if @properties.any? %>
      <% @properties.each do |property| %>
        <div class="card-search-result">
          <a href="<%= property_path(property)%>" class="card-link">
            <img src="<%= property.image_urls.second %>" alt="" class="d-block" width="238" height="240" unless property.photos.first.nil?>
            <div class="d-flex justify-content-end w-100">
            <%= link_to edit_property_path(property) do %>
              <i class="fa-solid fa-pen-to-square search_edit_delete"></i>
            <% end %>
            <%= link_to delete_user_property_path(property),
              data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} do %>
              <i class="fa-solid fa-trash search_edit_delete"></i>
            <% end %>
            </div>
            <span class="prefecture">
              <p class="text-center"><%= property.city unless property.city.nil? %>,
              <%= property.prefecture %></span></p>
            <p class="property-info text-center">
              <%= "#{property.bedrooms} bedrooms | #{number_to_currency(property.price)}" %></p>
          </a>
        </div>
      <% end %>
     <% else %>
        <p>You have no properties listed.</p>
      <% end %>
  </div>