config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.

  get "up" => "rails/health#show", as: :rails_health_check

  root to: "pages#home"

  devise_for :users

  resources :consultations, only: :index

  resources :favourites, only: [:index, :destroy]

  resources :properties do
    resources :consultations, only: [:new, :create]
    resources :favourites, only: :create
  end

  get "/user_properties", to: 'properties#user_properties', as: 'user_properties'

  get "/faqs", to: 'pages#faqs', as: 'faqs'

  get "/services", to: 'pages#services', as: 'services'

  get "/subscribe", to: 'subscribers#create', as: 'subscribe'

  delete "properties/:id", to: "properties#destroy", as: 'delete_user_property'

  get "/user_properties/edit", to: "properties#edit"

  patch "/user_properties", to: "properties#update"

  post '/favourites/:property_id', to: "favourites#create"
  delete '/favourites/:id', to: "favourites#destroy"
end

# HUGH'S CUSTOM ROUTES THAT I AM UNSURE WHETHER WE WILL KEEP
# get '/user_bookings', to: 'bookings#user_bookings', as: 'user_bookings'
# get "search_result", to: 'properties#search_result', as: 'search_result'
#get '/user_properties/property_bookings', to: 'bookings#property_bookings', as: 'property_bookings'

app/views/shared/_accordion_item.html.erb
<div class="accordion-item">
  <h2 class="accordion-header">
    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapse<%= plan + index.to_s %>" aria-expanded="false" aria-controls="flush-collapse<%= plan + index.to_s %>">
      <%= title %>
    </button>
  </h2>
  <div id="flush-collapse<%= plan + index.to_s %>" class="accordion-collapse collapse" data-bs-parent="#accordionFlush<%= plan %>">
    <div class="accordion-body">
      <%= content %>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="p-3 mt-5 akiya-footer">
  <div class="container">
    <div class="row">
      <div class="col-4">
      <h4 class="mb-3">Akiya Access</h4>
      <p class="mb-3">Discover your dream home in Japan</p>
      <p>Join our community</p>
        <div>
          <a href="https://facebook.com" target="_blank" data-controller="clipboard" data-action="clipboard#copy">
            <button class="share-button facebook">
              <i class="fab fa-facebook-f"></i>
            </button>
            </button>
              </a>
              <a href="https://instagram.com" target="_blank" data-controller="clipboard" data-action="clipboard#copy">
              <button class="share-button instagram">
               <i class="fab fa-instagram"></i>
            </button>
              </a>
              <a href="https://youtube.com" target="_blank" data-controller="clipboard" data-action="clipboard#copy">
              <button class="share-button youtube">
                <i class="fa-brands fa-youtube"></i>
              </button>
            </a>
            <a href="https://tiktok.com" target="_blank" data-controller="clipboard" data-action="clipboard#copy">
              <button class="share-button tiktok">
               <i class="fa-brands fa-tiktok"></i>
              </button>
            </a>
        </div>
      </div>
      <div class="col-4">
      <h5 class="mb-3">Explore</h5>
      <p class="mb-3"><%= link_to "Services Packages", services_path %></p>
      <p class="mb-3"><%= link_to "FAQs", faqs_path %></p>
      <p class="mb-3"><%= link_to "Contact Us", "mailto:tdomoto88@gmail.com"  %></p>
      </div>
      <div class="col-4">
        <h5 class="mb-3">Subscribe to Our Newsletter</h5>
        <p class="mb-3">Get exclusive promotions & updates straight to your inbox.</p>
        <form class="input-group mb-3" action="/subscribe">
          <span class="input-group-text" id="basic-addon1">@</span>
          <input type="text" class="form-control" placeholder="Email" aria-label="Email" aria-describedby="basic-addon1" id="email" name="email">
          <button type="submit" class="btn-dark ps-2 pe-2">Subscribe</button>
        </form>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="AA-navbar">
  <div class="AA-navbar-left">
    <%= link_to root_path, class: "logo" do %>
      <%= image_tag "logo.png", alt: "Logo", class: "logo-image" %>
    <% end %>
  </div>
  <div class="AA-navbar-center">
    <p><%= link_to "Home", root_path %></p>
    <p><%= link_to "Services Packages", services_path %></p>
    <p><%= link_to "FAQs", faqs_path %></p>
  </div>
  <div class="AA-navbar-right">
    <div class="dropdown">
      <button
        class="dropdown <%= user_signed_in? ? "logged-in" : "btn dropdown-circle toggle-button" %>"
        type="button"
        id="dropdownMenuButton2"
        data-bs-toggle="dropdown"
        aria-expanded="false">
        <% unless user_signed_in? %>
          <i class="fas fa-bars"></i>
        <% end %>
      </button>
      <ul class="dropdown-menu dropdown-menu-dark ps-2" aria-labelledby="dropdownMenuButton2">
        <% if user_signed_in? && current_user.is_owner %>
          <li><%= link_to "Logout", destroy_user_session_path, data: { turbo_method: "delete" } %></li>
          <li><%= link_to "View Favourites", favourites_path %></li>
          <li><%= link_to "Add a property", new_property_path %></li>
          <li><%= link_to "Your Properties", user_properties_path %></li>
        <% elsif user_signed_in? %>
          <li><%= link_to "Logout", destroy_user_session_path, data: { turbo_method: "delete" } %></li>
          <li><%= link_to "View Favourites", favourites_path %></li>
          <li><%= link_to "List your Property", edit_user_registration_path %></li>
        <% else %>
          <li><%= link_to "Login", user_session_path %></li>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>